services:

  mongodb:
    container_name: mongodb
    image: mongo
    hostname: mongodb
    volumes:
      - ${BASE_PATH}/scripts/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ${BASE_PATH}/data/mongo:/data/
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_ROOT_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DB}"
      MONGO_INITDB_USER: "${MONGO_USER}"
      MONGO_INITDB_PWD: "${MONGO_PASSWORD}"
    ports:
      - 27017:27017

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: "65535"
